#!/usr/bin/env bash
# Regenerate `dlmalloc.ll` from `temen_dlmalloc.c` + the vendored `malloc.c`. Needs clang and opt of the
# LLVM major `scripts/ci/install-llvm.sh` pins (e.g. `PATH=/usr/lib/llvm-22/bin:$PATH ./gen.sh`).
#
# The unit keeps only the entry points the on-ramp aliases (`HEAP_API` in src/lib.rs) and what they
# reach, and every symbol and named type it defines is renamed into the reserved `__temen_dl.`
# namespace, so merging it into a guest can never collide with a guest's own names.
set -euo pipefail
cd "$(dirname "$0")"
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

clang -O2 -g0 -fno-strict-aliasing -fno-vectorize -fno-slp-vectorize \
  -emit-llvm -S temen_dlmalloc.c -o "$tmp/raw.ll"
opt -S -passes='internalize,globaldce' \
  -internalize-public-api-list=dlmalloc,dlfree,dlcalloc,dlrealloc,dlmemalign,dlposix_memalign \
  "$tmp/raw.ll" -o "$tmp/pruned.ll"

perl -e '
  local $/; my $src = <STDIN>;
  my %sym = map { $_ => 1 } ($src =~ /^define [^@]*@([\w.\$]+)\(/mg, $src =~ /^@([\w.\$]+) = /mg);
  my %ty = map { $_ => 1 } ($src =~ /^%([\w.]+) = type /mg);
  for my $n (sort { length($b) <=> length($a) } keys %sym) {
    $src =~ s/@\Q$n\E(?![\w.\$])/\@__temen_dl.$n/g;
  }
  for my $n (sort { length($b) <=> length($a) } keys %ty) {
    (my $short = $n) =~ s/^struct\.//;
    $src =~ s/%\Q$n\E(?![\w.])/%__temen_dl.$short/g;
  }
  $src =~ s/^; ModuleID = .*\n//m;
  print "; GENERATED by gen.sh from temen_dlmalloc.c + malloc.c (dlmalloc 2.8.6, MIT-0). Do not edit.\n";
  print $src;
' <"$tmp/pruned.ll" >dlmalloc.ll
echo "wrote $(pwd)/dlmalloc.ll"
