//! **#1025 slice 3c — the driver-guest port, step 10: hexer's lowering, op-13-spawned from the guest.**
//! Step 9 ran nimsem (sema) as an op-13 §14 child of a Rust-on-Temen driver guest. This runs the *next*
//! phase the same way: the guest `instantiate_module`s (op 13) the real child-entry **hexer** over a
//! shared memfs, re-granting three caps `{fs, stdout, exit}` — hexer needs no `exec` (unlike nimsem it
//! spawns nothing; it reads a `.s.nif` and lowers it). It reads the semchecked system module nimsem left
//! behind (`hexer c nimcache/sysvq0asl.s.nif`) and writes the Leng `sysvq0asl.x.nif`, which the host
//! asserts is **byte-identical** to the committed expected.
//!
//! **Committed, wire-format-coupled assets** (regenerated by `demos/nim_frontend/build_frontend.sh`; see
//! its README): `hexer_ce.temen.gz` (hexer built `--child-entry`), the `sysvq0asl.s.nif.gz` +
//! `sysvq0asl.s.idx.nif` hexer reads (shared with step 9 — that is nimsem's output), and
//! `sysvq0asl.x.nif.gz` (the expected Leng — hexer is deterministic for a fixed input). If an
//! IR/ABI/encoder change breaks decode/verify or the op-13 spawn, or a frontend bump changes the emitted
//! Leng, this gate fails — regenerate together. The byte-exact-vs-*native* chain stays in the
//! toolchain-gated `build_frontend.sh` (issue #1221).
//!
//! Heavy: the guest carves hexer a 256 MiB window (the no-GC system lowering peaks high), so the guest
//! runs in a ~1 GiB window. Gated Linux + rustc + gzip.

#![cfg(target_os = "linux")]

use std::io::Write;
use std::path::Path;
use std::process::{Command, Stdio};
use std::sync::Arc;

use temen_interp::{run_with_host, ForkedProc, Host, HostProc, HostProcFork, StreamRole, Value};

const HEXER_CE_GZ: &[u8] =
    include_bytes!("../../temen-run/demos/nim_frontend/fixtures/hexer_ce.temen.gz");
const SYS_SNIF_GZ: &[u8] =
    include_bytes!("../../temen-run/demos/nim_frontend/fixtures/sysvq0asl.s.nif.gz");
const SYS_SIDX: &[u8] =
    include_bytes!("../../temen-run/demos/nim_frontend/fixtures/sysvq0asl.s.idx.nif");
const EXPECTED_XNIF_GZ: &[u8] =
    include_bytes!("../../temen-run/demos/nim_frontend/fixtures/sysvq0asl.x.nif.gz");

/// The driver guest: resolve `{inst, hexer, fs, stdout, exit}`, build the three-cap op-13 grant list +
/// the `hexer c nimcache/sysvq0asl.s.nif` argv in a 256 MiB carve, spawn hexer, join.
const GUEST: &str = r##"#![no_std]
#![allow(internal_features)]
#[panic_handler]
fn ph(_: &core::panic::PanicInfo) -> ! { loop {} }
#[no_mangle]
pub extern "C" fn rust_eh_personality() {}

#[repr(C, align(65536))]
struct Pool([u8; 536870912]); // 512 MiB of static -> a 256 MiB carve for hexer (window rounds to 1 GiB)
static mut POOL: Pool = Pool([0; 536870912]);

extern "C" {
    fn __vm_cap_resolve(name: *const u8, len: i64) -> i32;
    fn __vm_instantiate(
        inst: i32, module: i64, grants_ptr: i64, grants_n: i64,
        entry: i64, off: i64, size_log2: i64, quota: i64,
    ) -> i64;
    fn __vm_join(inst: i32, child: i64) -> i64;
}

unsafe fn wr(p: i64, b: u8) { (p as *mut u8).write(b); }

unsafe fn put_rec(base: i64, i: i64, name_off: i64, name_len: u32, handle: i32) {
    let rec = (base + i * 16) as *mut u32;
    rec.add(0).write(name_off as u32);
    rec.add(1).write(name_len);
    rec.add(2).write(handle as u32);
    rec.add(3).write(0);
}

#[no_mangle]
pub extern "C" fn run() -> i64 {
    unsafe {
        let inst = __vm_cap_resolve(b"inst".as_ptr(), 4);
        let hexer = __vm_cap_resolve(b"hexer".as_ptr(), 5);
        let fs = __vm_cap_resolve(b"fs".as_ptr(), 2);
        let out = __vm_cap_resolve(b"stdout".as_ptr(), 6);
        let ex = __vm_cap_resolve(b"exit".as_ptr(), 4);
        if inst < 0 || hexer < 0 || fs < 0 || out < 0 || ex < 0 { return -1; }
        let base = core::ptr::addr_of_mut!(POOL) as i64;

        // Three grant records {fs, stdout, exit} at base+0.., their names packed at base+64. POOL sits
        // above the module NULL guard, so base+0 is a legal writable address.
        let nm = (base + 64) as *mut u8;
        let names: [&[u8]; 3] = [b"fs", b"stdout", b"exit"];
        let mut off = 0usize; let mut ai = 0;
        let mut noffs: [i64; 3] = [0; 3];
        while ai < 3 {
            noffs[ai] = base + 64 + off as i64;
            let s = names[ai]; let mut j = 0;
            while j < s.len() { nm.add(off + j).write(s[j]); j += 1; }
            off += s.len(); ai += 1;
        }
        put_rec(base, 0, noffs[0], 2, fs);
        put_rec(base, 1, noffs[1], 6, out);
        put_rec(base, 2, noffs[2], 4, ex);

        // 256 MiB carve, 2^28-aligned within the window.
        let mask: i64 = (1 << 28) - 1;
        let carve = (base + 128 + mask) & !mask;

        // argv at carve + 16512 (the child's module_args_base): "hexer" "c" "nimcache/sysvq0asl.s.nif"
        let a = carve + 16512;
        (a as *mut u32).add(0).write(3);
        (a as *mut u32).add(1).write(0);
        let args: [&[u8]; 3] = [b"hexer", b"c", b"nimcache/sysvq0asl.s.nif"];
        let mut p = 8i64; let mut i = 0;
        while i < 3 {
            let s = args[i]; let mut j = 0;
            while j < s.len() { wr(a + p, s[j]); p += 1; j += 1; }
            wr(a + p, 0); p += 1; i += 1;
        }

        let child = __vm_instantiate(inst, hexer as i64, base, 3, 0, carve, 28, 0);
        __vm_join(inst, child)
    }
}
"##;

fn rustc_emit_ll(src: &Path, ll: &Path) -> bool {
    Command::new("rustc")
        .args([
            "--edition",
            "2021",
            "-O",
            "-Cpanic=abort",
            "--emit=llvm-ir",
            "--crate-type=cdylib",
        ])
        .arg(src)
        .arg("-o")
        .arg(ll)
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

/// Inflate a gzip blob via `gzip -dc` (own thread for the stdin write — the inflated blob overflows the
/// OS pipe buffer; same as `nifler_child_asset.rs`).
fn inflate(gz: &[u8]) -> Option<Vec<u8>> {
    let mut c = Command::new("gzip")
        .args(["-dc"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .spawn()
        .ok()?;
    let mut stdin = c.stdin.take().unwrap();
    let gz = gz.to_vec();
    let w = std::thread::spawn(move || {
        let _ = stdin.write_all(&gz);
    });
    let out = c.wait_with_output().ok()?;
    w.join().ok()?;
    out.status.success().then_some(out.stdout)
}

#[test]
fn rust_driver_guest_op13_spawns_real_hexer_byte_exact() {
    let (Some(hexer_bytes), Some(s_nif), Some(expected)) = (
        inflate(HEXER_CE_GZ),
        inflate(SYS_SNIF_GZ),
        inflate(EXPECTED_XNIF_GZ),
    ) else {
        eprintln!("note: skipping (gzip unavailable)");
        return;
    };

    let dir = std::env::temp_dir().join(format!("rust_driver_hexer_{}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();
    let src = dir.join("g.rs");
    let ll = dir.join("g.ll");
    std::fs::write(&src, GUEST).unwrap();
    if !rustc_emit_ll(&src, &ll) {
        eprintln!("note: skipping (rustc unavailable)");
        return;
    }
    let t = temen_llvm::translate_ll_path(&ll).expect("translate hexer guest");
    temen_verify::verify_module(&t.module).expect("driver verifies");
    let entry = t
        .exports
        .iter()
        .find(|(n, _)| n == "run")
        .expect("exports run")
        .1;
    let sp = t.entry_sp as i64;

    // The shared memfs: the semchecked system module nimsem produced (`.s.nif` + its `.s.idx.nif`), which
    // hexer reads and lowers. This is exactly nimsem's step-9 output handed to the next phase.
    let files = vec![
        ("nimcache/sysvq0asl.s.nif".into(), s_nif),
        ("nimcache/sysvq0asl.s.idx.nif".into(), SYS_SIDX.to_vec()),
    ];
    let (factory, handle) = temen_run::fs::mem_fs_shared_factory(files, vec!["nimcache".into()]);
    let factory = Arc::new(factory);

    let hexer = temen_encode::decode_module(&hexer_bytes).expect("decode hexer_ce");
    temen_verify::verify_module(&hexer).expect("hexer_ce verifies");

    let mut host = Host::new();
    let win = 1u64 << t.module.memory.as_ref().expect("driver window").size_log2;
    let inst = host.grant_instantiator(0, win);
    let modh = host.grant_module(&hexer);
    let fs_init: HostProc = (*factory)();
    let fs_fork: HostProcFork = {
        let f = Arc::clone(&factory);
        Arc::new(move |_pid| ForkedProc::shared((*f)()))
    };
    let fs_h = host.grant_host_proc_forkable(fs_init, fs_fork);
    let stdout_h = host.grant_stream(StreamRole::Out);
    let exit_h = host.grant_exit();
    host.register_cap_name("inst", inst);
    host.register_cap_name("hexer", modh);
    host.register_cap_name("fs", fs_h);
    host.register_cap_name("stdout", stdout_h);
    host.register_cap_name("exit", exit_h);

    let mut fuel = 2_000_000_000_000u64;
    let r = run_with_host(&t.module, entry, &[Value::I64(sp)], &mut fuel, &mut host);
    assert!(
        matches!(r.as_deref(), Ok([Value::I64(0)]) | Ok([Value::I32(0)])),
        "the guest-spawned hexer child joined with status 0: {r:?}"
    );

    let (produced, _) = handle.seed();
    let x_nif = produced
        .iter()
        .find(|(k, _)| k == "nimcache/sysvq0asl.x.nif")
        .map(|(_, v)| v.clone())
        .expect("guest-spawned hexer produced no sysvq0asl.x.nif");
    assert_eq!(
        x_nif, expected,
        "the guest-spawned hexer's lowering must be byte-identical to the committed expected Leng \
         (hexer is deterministic for a fixed input); regenerate the fixtures together if a frontend/wire \
         change moves it"
    );
}
