//! **#1025 slice 3c — the driver-guest port, step 9: the real nimsem, op-13-spawned from the guest.**
//! Steps 3–8 ported nimc's phase-1 crawl and its dependency order into the sandbox. This runs the first
//! real *phase* under the guest's own authority: a Rust-on-Temen driver guest `instantiate_module`s (§14
//! op 13) the real child-entry **nimsem** over a shared memfs, re-granting it four caps `{fs, stdout,
//! exit, exec}` — the `exec` a `domain_exec` over the *same* store, so nimsem-the-child drives **nifler
//! grandchildren** to parse the stdlib it imports (nimsem is itself a driver). nimsem semchecks the
//! system module (`--isSystem`) and writes `sysvq0asl.s.nif`, which the host asserts is **byte-identical**
//! to the committed expected.
//!
//! **Committed, wire-format-coupled assets** (regenerated by `demos/nim_frontend/build_frontend.sh`; see
//! its README): `nimsem_ce.temen.gz` (nimsem built `--child-entry`), `syslib.tar.gz` (the 26-file system
//! import closure the nifler grandchildren parse), `sysvq0asl.p.nif` (the seeded parsed system module),
//! and `sysvq0asl.s.nif.gz` (the expected sema output — nimsem's is deterministic for a fixed memfs). The
//! `exec`'s nifler is the already-committed top-level `browser/web/assets/nifler.temen.gz`. If an
//! IR/ABI/encoder change breaks decode/verify or the op-13 spawn, or a frontend bump changes the emitted
//! NIF, this gate fails — regenerate the assets and the expected together. The full byte-exact-vs-*native*
//! chain (and the JIT chain) stays in the toolchain-gated `build_frontend.sh` (issue #1221).
//!
//! Heavy: the guest carves nimsem a 256 MiB window (its no-GC system semcheck peaks there), so the guest
//! runs in a ~1 GiB window and the test takes tens of seconds. Gated Linux + rustc + gzip + tar.

#![cfg(target_os = "linux")]

use std::io::Write;
use std::path::Path;
use std::process::{Command, Stdio};
use std::sync::Arc;

use temen_interp::{run_with_host, ForkedProc, Host, HostProc, HostProcFork, StreamRole, Value};
use temen_run::exec::{domain_exec_with_fs, DomainProgram};
use temen_run::{instantiate, HostCap, Limits};

const NIMSEM_CE_GZ: &[u8] =
    include_bytes!("../../temen-run/demos/nim_frontend/fixtures/nimsem_ce.temen.gz");
const SYSLIB_TAR_GZ: &[u8] =
    include_bytes!("../../temen-run/demos/nim_frontend/fixtures/syslib.tar.gz");
const SYS_PNIF: &[u8] =
    include_bytes!("../../temen-run/demos/nim_frontend/fixtures/sysvq0asl.p.nif");
const EXPECTED_SNIF_GZ: &[u8] =
    include_bytes!("../../temen-run/demos/nim_frontend/fixtures/sysvq0asl.s.nif.gz");
// The exec's nifler: the already-committed top-level parse phase (paramless `_start`, run as a subprocess).
const NIFLER_TL_GZ: &[u8] = include_bytes!("../../../browser/web/assets/nifler.temen.gz");

/// The driver guest: resolve `{inst, nimsem, fs, stdout, exit, exec}`, build the four-cap op-13 grant
/// list + the `nimsem … --isSystem nimcache/sysvq0asl.p.nif` argv in a 256 MiB carve, spawn nimsem, join.
const GUEST: &str = r##"#![no_std]
#![allow(internal_features)]
#[panic_handler]
fn ph(_: &core::panic::PanicInfo) -> ! { loop {} }
#[no_mangle]
pub extern "C" fn rust_eh_personality() {}

#[repr(C, align(65536))]
struct Pool([u8; 536870912]); // 512 MiB of static -> a 256 MiB carve for nimsem (window rounds to 1 GiB)
static mut POOL: Pool = Pool([0; 536870912]);

extern "C" {
    fn __vm_cap_resolve(name: *const u8, len: i64) -> i32;
    fn __vm_instantiate(
        inst: i32, module: i64, grants_ptr: i64, grants_n: i64,
        entry: i64, off: i64, size_log2: i64, quota: i64,
    ) -> i64;
    fn __vm_join(inst: i32, child: i64) -> i64;
}

unsafe fn wr(p: i64, b: u8) { (p as *mut u8).write(b); }

unsafe fn put_rec(base: i64, i: i64, name_off: i64, name_len: u32, handle: i32) {
    let rec = (base + i * 16) as *mut u32;
    rec.add(0).write(name_off as u32);
    rec.add(1).write(name_len);
    rec.add(2).write(handle as u32);
    rec.add(3).write(0);
}

#[no_mangle]
pub extern "C" fn run() -> i64 {
    unsafe {
        let inst = __vm_cap_resolve(b"inst".as_ptr(), 4);
        let nimsem = __vm_cap_resolve(b"nimsem".as_ptr(), 6);
        let fs = __vm_cap_resolve(b"fs".as_ptr(), 2);
        let out = __vm_cap_resolve(b"stdout".as_ptr(), 6);
        let ex = __vm_cap_resolve(b"exit".as_ptr(), 4);
        let exe = __vm_cap_resolve(b"exec".as_ptr(), 4);
        if inst < 0 || nimsem < 0 || fs < 0 || out < 0 || ex < 0 || exe < 0 { return -1; }
        let base = core::ptr::addr_of_mut!(POOL) as i64;

        // Four grant records {fs, stdout, exit, exec} at base+0.., their names packed at base+64.
        // POOL sits above the module NULL guard, so base+0 is a legal writable address (unlike a
        // guarded module's low window — see nifler_child_asset.rs / the #1094 driver migration).
        let nm = (base + 64) as *mut u8;
        let names: [&[u8]; 4] = [b"fs", b"stdout", b"exit", b"exec"];
        let mut off = 0usize; let mut ai = 0;
        let mut noffs: [i64; 4] = [0; 4];
        while ai < 4 {
            noffs[ai] = base + 64 + off as i64;
            let s = names[ai]; let mut j = 0;
            while j < s.len() { nm.add(off + j).write(s[j]); j += 1; }
            off += s.len(); ai += 1;
        }
        put_rec(base, 0, noffs[0], 2, fs);
        put_rec(base, 1, noffs[1], 6, out);
        put_rec(base, 2, noffs[2], 4, ex);
        put_rec(base, 3, noffs[3], 4, exe);

        // 256 MiB carve, 2^28-aligned within the window.
        let mask: i64 = (1 << 28) - 1;
        let carve = (base + 128 + mask) & !mask;

        // argv at carve + 16512 (the child's module_args_base): argc/envc header then the strings.
        let a = carve + 16512;
        (a as *mut u32).add(0).write(6);
        (a as *mut u32).add(1).write(0);
        let args: [&[u8]; 6] = [
            b"nimsem", b"--define:nimNativeAlloc", b"--define:nimNativeIo", b"m",
            b"--isSystem", b"nimcache/sysvq0asl.p.nif",
        ];
        let mut p = 8i64; let mut i = 0;
        while i < 6 {
            let s = args[i]; let mut j = 0;
            while j < s.len() { wr(a + p, s[j]); p += 1; j += 1; }
            wr(a + p, 0); p += 1; i += 1;
        }

        let child = __vm_instantiate(inst, nimsem as i64, base, 4, 0, carve, 28, 0);
        __vm_join(inst, child)
    }
}
"##;

fn rustc_emit_ll(src: &Path, ll: &Path) -> bool {
    Command::new("rustc")
        .args([
            "--edition",
            "2021",
            "-O",
            "-Cpanic=abort",
            "--emit=llvm-ir",
            "--crate-type=cdylib",
        ])
        .arg(src)
        .arg("-o")
        .arg(ll)
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

/// Inflate a gzip blob via `gzip -dc` (the inflated `.temen` overflows the OS pipe buffer, so the stdin
/// write runs on its own thread — same as `nifler_child_asset.rs`).
fn inflate(gz: &[u8]) -> Option<Vec<u8>> {
    let mut c = Command::new("gzip")
        .args(["-dc"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .spawn()
        .ok()?;
    let mut stdin = c.stdin.take().unwrap();
    let gz = gz.to_vec();
    let w = std::thread::spawn(move || {
        let _ = stdin.write_all(&gz);
    });
    let out = c.wait_with_output().ok()?;
    w.join().ok()?;
    out.status.success().then_some(out.stdout)
}

fn collect(dir: &Path, prefix: &str, out: &mut Vec<(String, Vec<u8>)>) {
    let mut stack = vec![dir.to_path_buf()];
    while let Some(d) = stack.pop() {
        for e in std::fs::read_dir(&d).unwrap() {
            let e = e.unwrap();
            let p = e.path();
            if e.file_type().map(|t| t.is_dir()).unwrap_or(false) {
                stack.push(p);
            } else {
                let rel = p
                    .strip_prefix(dir)
                    .unwrap()
                    .to_string_lossy()
                    .replace('\\', "/");
                out.push((format!("{prefix}{rel}"), std::fs::read(&p).unwrap()));
            }
        }
    }
}

/// Unpack `syslib.tar.gz` into `dir/std/…` (via the `tar` CLI); `None` if tar is unavailable.
fn unpack_syslib(dir: &Path) -> Option<()> {
    let tgz = dir.join("syslib.tar.gz");
    std::fs::write(&tgz, SYSLIB_TAR_GZ).ok()?;
    let ok = Command::new("tar")
        .arg("xzf")
        .arg(&tgz)
        .arg("-C")
        .arg(dir)
        .status()
        .map(|s| s.success())
        .unwrap_or(false);
    ok.then_some(())
}

#[test]
fn rust_driver_guest_op13_spawns_real_nimsem_byte_exact() {
    let (Some(nimsem_bytes), Some(nifler_bytes), Some(expected)) = (
        inflate(NIMSEM_CE_GZ),
        inflate(NIFLER_TL_GZ),
        inflate(EXPECTED_SNIF_GZ),
    ) else {
        eprintln!("note: skipping (gzip unavailable)");
        return;
    };

    let dir = std::env::temp_dir().join(format!("rust_driver_nimsem_{}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();
    let libdir = dir.join("lib");
    std::fs::create_dir_all(&libdir).unwrap();
    if unpack_syslib(&libdir).is_none() {
        eprintln!("note: skipping (tar unavailable)");
        return;
    }

    // Translate the driver guest.
    let src = dir.join("g.rs");
    let ll = dir.join("g.ll");
    std::fs::write(&src, GUEST).unwrap();
    if !rustc_emit_ll(&src, &ll) {
        eprintln!("note: skipping (rustc unavailable)");
        return;
    }
    let t = temen_llvm::translate_ll_path(&ll).expect("translate nimsem guest");
    temen_verify::verify_module(&t.module).expect("driver verifies");
    let entry = t
        .exports
        .iter()
        .find(|(n, _)| n == "run")
        .expect("exports run")
        .1;
    let sp = t.entry_sp as i64;

    // The shared memfs: the stdlib closure under lib/ (preserving std/ and flattened, as nimc seeds it)
    // plus the parsed system module. nimsem's nifler grandchildren parse the sources; nimsem reads back
    // the `.p.nif` they write into this same store.
    let mut files = vec![];
    collect(&libdir, "lib/", &mut files);
    let flat: Vec<(String, Vec<u8>)> = files
        .iter()
        .filter_map(|(k, v)| {
            k.strip_prefix("lib/std/")
                .map(|r| (format!("lib/{r}"), v.clone()))
        })
        .collect();
    files.extend(flat);
    files.push(("nimcache/sysvq0asl.p.nif".into(), SYS_PNIF.to_vec()));

    let (factory, handle) = temen_run::fs::mem_fs_shared_factory(files, vec!["nimcache".into()]);
    let factory = Arc::new(factory);

    // The exec cap nimsem re-uses to spawn nifler grandchildren over the SAME store.
    let nifler_inst = Arc::new(
        instantiate(temen_encode::decode_module(&nifler_bytes).expect("decode nifler"))
            .expect("inst nifler"),
    );
    let programs: Vec<DomainProgram> = ["nifler", "/bin/nifler"]
        .iter()
        .map(|n| DomainProgram {
            name: (*n).into(),
            instance: nifler_inst.clone(),
            limits: Limits::default(),
        })
        .collect();
    let child_fs = {
        let f = factory.clone();
        HostCap::host_proc(0, move || (f)())
    };
    let exec_cap = domain_exec_with_fs(programs, child_fs);

    let nimsem = temen_encode::decode_module(&nimsem_bytes).expect("decode nimsem_ce");
    temen_verify::verify_module(&nimsem).expect("nimsem_ce verifies");

    let mut host = Host::new();
    let win = 1u64 << t.module.memory.as_ref().expect("driver window").size_log2;
    let inst = host.grant_instantiator(0, win);
    let modh = host.grant_module(&nimsem);
    let fs_init: HostProc = (*factory)();
    let fs_fork: HostProcFork = {
        let f = Arc::clone(&factory);
        Arc::new(move |_pid| ForkedProc::shared((*f)()))
    };
    let fs_h = host.grant_host_proc_forkable(fs_init, fs_fork);
    let stdout_h = host.grant_stream(StreamRole::Out);
    let exit_h = host.grant_exit();
    let exec_h = exec_cap.install(&mut host, win);
    host.register_cap_name("inst", inst);
    host.register_cap_name("nimsem", modh);
    host.register_cap_name("fs", fs_h);
    host.register_cap_name("stdout", stdout_h);
    host.register_cap_name("exit", exit_h);
    host.register_cap_name("exec", exec_h);

    let mut fuel = 2_000_000_000_000u64;
    let r = run_with_host(&t.module, entry, &[Value::I64(sp)], &mut fuel, &mut host);
    assert!(
        matches!(r.as_deref(), Ok([Value::I64(0)]) | Ok([Value::I32(0)])),
        "the guest-spawned nimsem child joined with status 0: {r:?}"
    );

    let (produced, _) = handle.seed();
    let s_nif = produced
        .iter()
        .find(|(k, _)| k == "nimcache/sysvq0asl.s.nif")
        .map(|(_, v)| v.clone())
        .expect("guest-spawned nimsem produced no sysvq0asl.s.nif");
    assert_eq!(
        s_nif, expected,
        "the guest-spawned nimsem's system semcheck must be byte-identical to the committed expected \
         (a fixed memfs makes nimsem deterministic); regenerate the fixtures together if a frontend/wire \
         change moves it"
    );
}
