//! **#1025 slice 3c — the driver-guest port, step 9: the real nimsem, spawned from the guest.**
//! Steps 3–8 ported nimc's phase-1 crawl and its dependency order into the sandbox. This runs the first
//! real *phase* under the guest's own authority: a Rust-on-Temen driver guest spawns (§14, the shared
//! `vm_spawn`: its own window) the real child-entry **nimsem** over a shared memfs, re-granting it four caps `{fs, stdout,
//! exit, exec}` — the `exec` a `domain_exec` over the *same* store, so nimsem-the-child drives **nifler
//! grandchildren** to parse the stdlib it imports (nimsem is itself a driver). nimsem semchecks the
//! system module (`--isSystem`) and writes `sysvq0asl.s.nif`, which the host asserts is **byte-identical**
//! to the committed expected.
//!
//! **Committed, wire-format-coupled assets** (regenerated by `demos/nim_frontend/build_frontend.sh`; see
//! its README): `nimsem_ce.temen.gz` (nimsem built `--child-entry`), `syslib.tar.gz` (the 26-file system
//! import closure the nifler grandchildren parse), `sysvq0asl.p.nif` (the seeded parsed system module),
//! and `sysvq0asl.s.nif.gz` (the expected sema output — nimsem's is deterministic for a fixed memfs). The
//! `exec`'s nifler is the already-committed top-level `browser/web/assets/nifler.temen.gz`. If an
//! IR/ABI/encoder change breaks decode/verify or the spawn, or a frontend bump changes the emitted
//! NIF, this gate fails — regenerate the assets and the expected together. The full byte-exact-vs-*native*
//! chain (and the JIT chain) stays in the toolchain-gated `build_frontend.sh` (issue #1221).
//!
//! Heavy: nimsem's no-GC system semcheck grows its heap well past its declared window, into the
//! window's reserved tail, and the test takes tens of seconds. Gated Linux + rustc + gzip + tar.

#![cfg(target_os = "linux")]

use std::io::Write;
use std::path::Path;
use std::process::{Command, Stdio};
use std::sync::Arc;

use temen_interp::{run_with_host, ForkedProc, Host, HostProcFork, StreamRole, Value};
use temen_run::exec::{domain_exec_with_fs, DomainProgram};
use temen_run::{instantiate, HostCap, Limits};

const NIMSEM_CE_GZ: &[u8] =
    include_bytes!("../../temen-run/demos/nim_frontend/fixtures/nimsem_ce.temen.gz");
const SYSLIB_TAR_GZ: &[u8] =
    include_bytes!("../../temen-run/demos/nim_frontend/fixtures/syslib.tar.gz");
const SYS_PNIF: &[u8] =
    include_bytes!("../../temen-run/demos/nim_frontend/fixtures/sysvq0asl.p.nif");
const EXPECTED_SNIF_GZ: &[u8] =
    include_bytes!("../../temen-run/demos/nim_frontend/fixtures/sysvq0asl.s.nif.gz");
// The exec's nifler: the already-committed top-level parse phase (paramless `_start`, run as a subprocess).
const NIFLER_TL_GZ: &[u8] = include_bytes!("../../../browser/web/assets/nifler.temen.gz");

/// The driver guest: resolve `{inst, nimsem, budget, fs, stdout, exit, exec}`, spawn nimsem with the
/// four caps re-granted and argv `nimsem … --isSystem nimcache/sysvq0asl.p.nif` (the shared `vm_spawn`,
/// appended), join.
const GUEST: &str = r##"#![no_std]
#![allow(internal_features)]
#[panic_handler]
fn ph(_: &core::panic::PanicInfo) -> ! { loop {} }
#[no_mangle]
pub extern "C" fn rust_eh_personality() {}

extern "C" {
    fn __vm_cap_resolve(name: *const u8, len: i64) -> i32;
    fn __vm_join(inst: i32, child: i64) -> i64;
}

#[no_mangle]
pub extern "C" fn run() -> i64 {
    unsafe {
        let inst = __vm_cap_resolve(b"inst".as_ptr(), 4);
        let nimsem = __vm_cap_resolve(b"nimsem".as_ptr(), 6);
        let budget = __vm_cap_resolve(b"budget".as_ptr(), 6);
        let fs = __vm_cap_resolve(b"fs".as_ptr(), 2);
        let out = __vm_cap_resolve(b"stdout".as_ptr(), 6);
        let ex = __vm_cap_resolve(b"exit".as_ptr(), 4);
        let exe = __vm_cap_resolve(b"exec".as_ptr(), 4);
        if inst < 0 || nimsem < 0 || budget < 0 || fs < 0 || out < 0 || ex < 0 || exe < 0 {
            return -1;
        }
        let child = vm_spawn(
            inst,
            budget,
            nimsem,
            &[(b"fs", fs), (b"stdout", out), (b"exit", ex), (b"exec", exe)],
            &[
                b"nimsem", b"--define:nimNativeAlloc", b"--define:nimNativeIo", b"m",
                b"--isSystem", b"nimcache/sysvq0asl.p.nif",
            ],
        );
        __vm_join(inst, child)
    }
}
"##;

/// The shared guest-side spawn, appended to every driver guest's source.
const VM_SPAWN: &str = include_str!("support/guest_vm_spawn.rs");

fn rustc_emit_ll(src: &Path, ll: &Path) -> bool {
    Command::new("rustc")
        .args([
            "--edition",
            "2021",
            "-O",
            "-Cpanic=abort",
            "--emit=llvm-ir",
            "--crate-type=cdylib",
        ])
        .arg(src)
        .arg("-o")
        .arg(ll)
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

/// Inflate a gzip blob via `gzip -dc` (the inflated `.temen` overflows the OS pipe buffer, so the stdin
/// write runs on its own thread — same as `nifler_child_asset.rs`).
fn inflate(gz: &[u8]) -> Option<Vec<u8>> {
    let mut c = Command::new("gzip")
        .args(["-dc"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .spawn()
        .ok()?;
    let mut stdin = c.stdin.take().unwrap();
    let gz = gz.to_vec();
    let w = std::thread::spawn(move || {
        let _ = stdin.write_all(&gz);
    });
    let out = c.wait_with_output().ok()?;
    w.join().ok()?;
    out.status.success().then_some(out.stdout)
}

fn collect(dir: &Path, prefix: &str, out: &mut Vec<(String, Vec<u8>)>) {
    let mut stack = vec![dir.to_path_buf()];
    while let Some(d) = stack.pop() {
        for e in std::fs::read_dir(&d).unwrap() {
            let e = e.unwrap();
            let p = e.path();
            if e.file_type().map(|t| t.is_dir()).unwrap_or(false) {
                stack.push(p);
            } else {
                let rel = p
                    .strip_prefix(dir)
                    .unwrap()
                    .to_string_lossy()
                    .replace('\\', "/");
                out.push((format!("{prefix}{rel}"), std::fs::read(&p).unwrap()));
            }
        }
    }
}

/// Unpack `syslib.tar.gz` into `dir/std/…` (via the `tar` CLI); `None` if tar is unavailable.
fn unpack_syslib(dir: &Path) -> Option<()> {
    let tgz = dir.join("syslib.tar.gz");
    std::fs::write(&tgz, SYSLIB_TAR_GZ).ok()?;
    let ok = Command::new("tar")
        .arg("xzf")
        .arg(&tgz)
        .arg("-C")
        .arg(dir)
        .status()
        .map(|s| s.success())
        .unwrap_or(false);
    ok.then_some(())
}

#[test]
fn rust_driver_guest_op13_spawns_real_nimsem_byte_exact() {
    let (Some(nimsem_bytes), Some(nifler_bytes), Some(expected)) = (
        inflate(NIMSEM_CE_GZ),
        inflate(NIFLER_TL_GZ),
        inflate(EXPECTED_SNIF_GZ),
    ) else {
        eprintln!("note: skipping (gzip unavailable)");
        return;
    };

    let dir = std::env::temp_dir().join(format!("rust_driver_nimsem_{}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();
    let libdir = dir.join("lib");
    std::fs::create_dir_all(&libdir).unwrap();
    if unpack_syslib(&libdir).is_none() {
        eprintln!("note: skipping (tar unavailable)");
        return;
    }

    // Translate the driver guest.
    let src = dir.join("g.rs");
    let ll = dir.join("g.ll");
    std::fs::write(&src, format!("{GUEST}\n{VM_SPAWN}")).unwrap();
    if !rustc_emit_ll(&src, &ll) {
        eprintln!("note: skipping (rustc unavailable)");
        return;
    }
    let t = temen_llvm::translate_ll_path(&ll).expect("translate nimsem guest");
    temen_verify::verify_module(&t.module).expect("driver verifies");
    let entry = t
        .exports
        .iter()
        .find(|(n, _)| n == "run")
        .expect("exports run")
        .1;
    let sp = t.entry_sp as i64;

    // The shared memfs: the stdlib closure under lib/ (preserving std/ and flattened, as nimc seeds it)
    // plus the parsed system module. nimsem's nifler grandchildren parse the sources; nimsem reads back
    // the `.p.nif` they write into this same store.
    let mut files = vec![];
    collect(&libdir, "lib/", &mut files);
    let flat: Vec<(String, Vec<u8>)> = files
        .iter()
        .filter_map(|(k, v)| {
            k.strip_prefix("lib/std/")
                .map(|r| (format!("lib/{r}"), v.clone()))
        })
        .collect();
    files.extend(flat);
    files.push(("nimcache/sysvq0asl.p.nif".into(), SYS_PNIF.to_vec()));

    let (factory, handle) = temen_run::fs::mem_fs_shared_factory(files, vec!["nimcache".into()]);
    let factory = Arc::new(factory);

    // The exec cap nimsem re-uses to spawn nifler grandchildren over the SAME store.
    let nifler_inst = Arc::new(
        instantiate(temen_encode::decode_module(&nifler_bytes).expect("decode nifler"))
            .expect("inst nifler"),
    );
    let programs: Vec<DomainProgram> = ["nifler", "/bin/nifler"]
        .iter()
        .map(|n| DomainProgram {
            name: (*n).into(),
            instance: nifler_inst.clone(),
            limits: Limits::default(),
        })
        .collect();
    let child_fs = {
        let f = factory.clone();
        HostCap::host_proc(0, move || (f)())
    };
    let exec_cap = domain_exec_with_fs(programs, child_fs);

    let nimsem = temen_encode::decode_module(&nimsem_bytes).expect("decode nimsem_ce");
    temen_verify::verify_module(&nimsem).expect("nimsem_ce verifies");

    let mut host = Host::new();
    let win = 1u64 << t.module.memory.as_ref().expect("driver window").size_log2;
    let inst = host.grant_instantiator(0, win);
    let modh = host.grant_module(&nimsem);
    // nimsem's window, paid from this and returned when it ends.
    let budget = host.grant_budget(-1, 1 << nimsem.memory.expect("nimsem window").size_log2, -1);
    let (fs_init, fs_init_state) = (*factory)();
    let fs_fork: HostProcFork = {
        let f = Arc::clone(&factory);
        Arc::new(move |_pid| {
            let (h, s) = (*f)();
            ForkedProc::shared(h, s)
        })
    };
    let fs_h = host.grant_host_proc_forkable(fs_init, fs_fork, fs_init_state);
    let stdout_h = host.grant_stream(StreamRole::Out);
    let exit_h = host.grant_exit();
    let exec_h = exec_cap.install(&mut host, win);
    host.register_cap_name("inst", inst);
    host.register_cap_name("nimsem", modh);
    host.register_cap_name("budget", budget);
    host.register_cap_name("fs", fs_h);
    host.register_cap_name("stdout", stdout_h);
    host.register_cap_name("exit", exit_h);
    host.register_cap_name("exec", exec_h);

    let mut fuel = 2_000_000_000_000u64;
    let r = run_with_host(&t.module, entry, &[Value::I64(sp)], &mut fuel, &mut host);
    assert!(
        matches!(r.as_deref(), Ok([Value::I64(0)]) | Ok([Value::I32(0)])),
        "the guest-spawned nimsem child joined with status 0: {r:?}"
    );

    let (produced, _) = handle.seed();
    let s_nif = produced
        .iter()
        .find(|(k, _)| k == "nimcache/sysvq0asl.s.nif")
        .map(|(_, v)| v.clone())
        .expect("guest-spawned nimsem produced no sysvq0asl.s.nif");
    assert_eq!(
        s_nif, expected,
        "the guest-spawned nimsem's system semcheck must be byte-identical to the committed expected \
         (a fixed memfs makes nimsem deterministic); regenerate the fixtures together if a frontend/wire \
         change moves it"
    );
}
