//! **#1025 slice 3c — the driver-guest port, step 10: hexer's lowering, spawned from the guest.**
//! Step 9 ran nimsem (sema) as a §14 child of a Rust-on-Temen driver guest. This runs the *next* phase
//! the same way: the guest spawns the real child-entry **hexer** (the shared `vm_spawn`: its own window)
//! over a shared memfs, re-granting three caps `{fs, stdout, exit}` — hexer needs no `exec` (unlike nimsem it
//! spawns nothing; it reads a `.s.nif` and lowers it). It reads the semchecked system module nimsem left
//! behind (`hexer c nimcache/sysvq0asl.s.nif`) and writes the Leng `sysvq0asl.x.nif`, which the host
//! asserts is **byte-identical** to the committed expected.
//!
//! **Committed, wire-format-coupled assets** (regenerated by `demos/nim_frontend/build_frontend.sh`; see
//! its README): `hexer_ce.temen.gz` (hexer built `--child-entry`), the `sysvq0asl.s.nif.gz` +
//! `sysvq0asl.s.idx.nif` hexer reads (shared with step 9 — that is nimsem's output), and
//! `sysvq0asl.x.nif.gz` (the expected Leng — hexer is deterministic for a fixed input). If an
//! IR/ABI/encoder change breaks decode/verify or the spawn, or a frontend bump changes the emitted
//! Leng, this gate fails — regenerate together. The byte-exact-vs-*native* chain stays in the
//! toolchain-gated `build_frontend.sh` (issue #1221).
//!
//! Heavy: hexer's no-GC system lowering grows its heap well past its declared window, into the window's
//! reserved tail. Gated Linux + rustc + gzip.

#![cfg(target_os = "linux")]

use std::io::Write;
use std::path::Path;
use std::process::{Command, Stdio};
use std::sync::Arc;

use temen_interp::{run_with_host, ForkedProc, Host, HostProcFork, StreamRole, Value};

const HEXER_CE_GZ: &[u8] =
    include_bytes!("../../temen-run/demos/nim_frontend/fixtures/hexer_ce.temen.gz");
const SYS_SNIF_GZ: &[u8] =
    include_bytes!("../../temen-run/demos/nim_frontend/fixtures/sysvq0asl.s.nif.gz");
const SYS_SIDX: &[u8] =
    include_bytes!("../../temen-run/demos/nim_frontend/fixtures/sysvq0asl.s.idx.nif");
const EXPECTED_XNIF_GZ: &[u8] =
    include_bytes!("../../temen-run/demos/nim_frontend/fixtures/sysvq0asl.x.nif.gz");

/// The driver guest: resolve `{inst, hexer, budget, fs, stdout, exit}`, spawn hexer with the three caps
/// re-granted and argv `hexer c nimcache/sysvq0asl.s.nif` (the shared `vm_spawn`, appended), join.
const GUEST: &str = r##"#![no_std]
#![allow(internal_features)]
#[panic_handler]
fn ph(_: &core::panic::PanicInfo) -> ! { loop {} }
#[no_mangle]
pub extern "C" fn rust_eh_personality() {}

extern "C" {
    fn __vm_cap_resolve(name: *const u8, len: i64) -> i32;
    fn __vm_join(inst: i32, child: i64) -> i64;
}

#[no_mangle]
pub extern "C" fn run() -> i64 {
    unsafe {
        let inst = __vm_cap_resolve(b"inst".as_ptr(), 4);
        let hexer = __vm_cap_resolve(b"hexer".as_ptr(), 5);
        let budget = __vm_cap_resolve(b"budget".as_ptr(), 6);
        let fs = __vm_cap_resolve(b"fs".as_ptr(), 2);
        let out = __vm_cap_resolve(b"stdout".as_ptr(), 6);
        let ex = __vm_cap_resolve(b"exit".as_ptr(), 4);
        if inst < 0 || hexer < 0 || budget < 0 || fs < 0 || out < 0 || ex < 0 { return -1; }
        let child = vm_spawn(
            inst,
            budget,
            hexer,
            &[(b"fs", fs), (b"stdout", out), (b"exit", ex)],
            &[b"hexer", b"c", b"nimcache/sysvq0asl.s.nif"],
        );
        __vm_join(inst, child)
    }
}
"##;

/// The shared guest-side spawn, appended to every driver guest's source.
const VM_SPAWN: &str = include_str!("support/guest_vm_spawn.rs");

fn rustc_emit_ll(src: &Path, ll: &Path) -> bool {
    Command::new("rustc")
        .args([
            "--edition",
            "2021",
            "-O",
            "-Cpanic=abort",
            "--emit=llvm-ir",
            "--crate-type=cdylib",
        ])
        .arg(src)
        .arg("-o")
        .arg(ll)
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

/// Inflate a gzip blob via `gzip -dc` (own thread for the stdin write — the inflated blob overflows the
/// OS pipe buffer; same as `nifler_child_asset.rs`).
fn inflate(gz: &[u8]) -> Option<Vec<u8>> {
    let mut c = Command::new("gzip")
        .args(["-dc"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .spawn()
        .ok()?;
    let mut stdin = c.stdin.take().unwrap();
    let gz = gz.to_vec();
    let w = std::thread::spawn(move || {
        let _ = stdin.write_all(&gz);
    });
    let out = c.wait_with_output().ok()?;
    w.join().ok()?;
    out.status.success().then_some(out.stdout)
}

#[test]
fn rust_driver_guest_op13_spawns_real_hexer_byte_exact() {
    let (Some(hexer_bytes), Some(s_nif), Some(expected)) = (
        inflate(HEXER_CE_GZ),
        inflate(SYS_SNIF_GZ),
        inflate(EXPECTED_XNIF_GZ),
    ) else {
        eprintln!("note: skipping (gzip unavailable)");
        return;
    };

    let dir = std::env::temp_dir().join(format!("rust_driver_hexer_{}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();
    let src = dir.join("g.rs");
    let ll = dir.join("g.ll");
    std::fs::write(&src, format!("{GUEST}\n{VM_SPAWN}")).unwrap();
    if !rustc_emit_ll(&src, &ll) {
        eprintln!("note: skipping (rustc unavailable)");
        return;
    }
    let t = temen_llvm::translate_ll_path(&ll).expect("translate hexer guest");
    temen_verify::verify_module(&t.module).expect("driver verifies");
    let entry = t
        .exports
        .iter()
        .find(|(n, _)| n == "run")
        .expect("exports run")
        .1;
    let sp = t.entry_sp as i64;

    // The shared memfs: the semchecked system module nimsem produced (`.s.nif` + its `.s.idx.nif`), which
    // hexer reads and lowers. This is exactly nimsem's step-9 output handed to the next phase.
    let files = vec![
        ("nimcache/sysvq0asl.s.nif".into(), s_nif),
        ("nimcache/sysvq0asl.s.idx.nif".into(), SYS_SIDX.to_vec()),
    ];
    let (factory, handle) = temen_run::fs::mem_fs_shared_factory(files, vec!["nimcache".into()]);
    let factory = Arc::new(factory);

    let hexer = temen_encode::decode_module(&hexer_bytes).expect("decode hexer_ce");
    temen_verify::verify_module(&hexer).expect("hexer_ce verifies");

    let mut host = Host::new();
    let win = 1u64 << t.module.memory.as_ref().expect("driver window").size_log2;
    let inst = host.grant_instantiator(0, win);
    let modh = host.grant_module(&hexer);
    // hexer's window, paid from this and returned when it ends.
    let budget = host.grant_budget(-1, 1 << hexer.memory.expect("hexer window").size_log2, 0);
    let (fs_init, fs_init_state) = (*factory)();
    let fs_fork: HostProcFork = {
        let f = Arc::clone(&factory);
        Arc::new(move |_pid| {
            let (h, s) = (*f)();
            ForkedProc::shared(h, s)
        })
    };
    let fs_h = host.grant_host_proc_forkable(fs_init, fs_fork, fs_init_state);
    let stdout_h = host.grant_stream(StreamRole::Out);
    let exit_h = host.grant_exit();
    host.register_cap_name("inst", inst);
    host.register_cap_name("hexer", modh);
    host.register_cap_name("budget", budget);
    host.register_cap_name("fs", fs_h);
    host.register_cap_name("stdout", stdout_h);
    host.register_cap_name("exit", exit_h);

    let mut fuel = 2_000_000_000_000u64;
    let r = run_with_host(&t.module, entry, &[Value::I64(sp)], &mut fuel, &mut host);
    assert!(
        matches!(r.as_deref(), Ok([Value::I64(0)]) | Ok([Value::I32(0)])),
        "the guest-spawned hexer child joined with status 0: {r:?}"
    );

    let (produced, _) = handle.seed();
    let x_nif = produced
        .iter()
        .find(|(k, _)| k == "nimcache/sysvq0asl.x.nif")
        .map(|(_, v)| v.clone())
        .expect("guest-spawned hexer produced no sysvq0asl.x.nif");
    assert_eq!(
        x_nif, expected,
        "the guest-spawned hexer's lowering must be byte-identical to the committed expected Leng \
         (hexer is deterministic for a fixed input); regenerate the fixtures together if a frontend/wire \
         change moves it"
    );
}
