/* Tcl full-init REPL guest — the "Full Tcl_Init" follow-up to `tcl_repl.c`. Where `tcl_repl.c` runs
 * the bare language core (`Tcl_CreateInterp` only, no filesystem), this driver runs a *complete* Tcl:
 * it registers an in-guest `Tcl_Filesystem` VFS that serves the Tcl script library from **embedded
 * byte arrays** (`tcl_library.h`, generated by `gen_tcl_library.py`), points `tcl_library` at the
 * VFS mount, and calls `Tcl_Init` — which sources `init.tcl` and unlocks `auto_load`/`unknown`/
 * `package`, the `clock`/`parray`/`history` script commands, and real `file`/`glob`.
 *
 * The VFS is the clean way to embed a script library in a sandboxed guest: its callbacks fill Tcl's
 * own `Tcl_StatBuf` in C (so there is **no libc `struct stat` ABI gap**), it needs **no filesystem
 * capability** (the scripts live in the guest binary), and it works identically native, on temen, and
 * in the browser. This is how embedded Tcl applications ship their library.
 *
 * Reads a Tcl script from stdin, evaluates it, prints the completion result — same REPL shape as
 * `tcl_repl.c`, but with the whole standard library available.
 */
#include <string.h>
#include <sys/stat.h>
#include "tcl.h"
#include "tcl_library.h" /* the embedded script library: `tcl_library[]` / `tcl_library_n` */

extern long read(int fd, void *buf, long n);

static const char *const MOUNT = "//tcllib"; /* the VFS mount point (a Tcl volume) */

/* ---- library lookup over the embedded entries ------------------------------------------------ */

/* The path relative to MOUNT (NULL if `vpath` is not under the mount; "" for the mount root). */
static const char *lib_rel(const char *vpath) {
    size_t ml = strlen(MOUNT);
    if (strncmp(vpath, MOUNT, ml) != 0)
        return 0;
    const char *rest = vpath + ml;
    return (*rest == '/') ? rest + 1 : rest;
}
static const TclLibEntry *lib_find(const char *vpath) {
    const char *rel = lib_rel(vpath);
    if (!rel || !*rel)
        return 0;
    for (int i = 0; i < tcl_library_n; i++)
        if (strcmp(tcl_library[i].name, rel) == 0)
            return &tcl_library[i];
    return 0;
}
/* True if `rel` names a directory: the root, or a strict path-prefix of some entry's directory. */
static int lib_is_dir(const char *rel) {
    if (!*rel)
        return 1;
    size_t rl = strlen(rel);
    for (int i = 0; i < tcl_library_n; i++) {
        const char *n = tcl_library[i].name;
        if (strncmp(n, rel, rl) == 0 && n[rl] == '/')
            return 1;
    }
    return 0;
}

/* ---- a minimal read-only in-memory Tcl channel (serves one embedded file) -------------------- */

typedef struct {
    const TclLibEntry *f;
    long pos;
} MemChan;

static int memInput(ClientData cd, char *buf, int toRead, int *ec) {
    MemChan *m = (MemChan *)cd;
    (void)ec;
    long avail = (long)m->f->len - m->pos;
    if (avail <= 0)
        return 0;
    int n = (toRead < avail) ? toRead : (int)avail;
    memcpy(buf, m->f->data + m->pos, n);
    m->pos += n;
    return n;
}
static int memClose(ClientData cd, Tcl_Interp *ip) {
    (void)ip;
    ckfree((char *)cd);
    return 0;
}
static void memWatch(ClientData cd, int mask) {
    (void)cd;
    (void)mask;
}
static int memHandle(ClientData cd, int dir, ClientData *hp) {
    (void)cd;
    (void)dir;
    (void)hp;
    return TCL_ERROR;
}
static int memSeek(ClientData cd, long off, int mode, int *ec) {
    MemChan *m = (MemChan *)cd;
    (void)ec;
    long p = (mode == SEEK_CUR) ? m->pos + off : (mode == SEEK_END) ? (long)m->f->len + off : off;
    if (p < 0)
        p = 0;
    if (p > (long)m->f->len)
        p = (long)m->f->len;
    m->pos = p;
    return (int)p;
}
static Tcl_ChannelType memChanType = {
    .typeName = "tcllibmem",
    .version = TCL_CHANNEL_VERSION_2,
    .closeProc = memClose,
    .inputProc = memInput,
    .seekProc = memSeek,
    .watchProc = memWatch,
    .getHandleProc = memHandle,
};

/* ---- the Tcl_Filesystem ---------------------------------------------------------------------- */

static int vfsPathInFs(Tcl_Obj *p, ClientData *cd) {
    (void)cd;
    return lib_rel(Tcl_GetString(p)) ? TCL_OK : -1;
}
static int vfsStat(Tcl_Obj *p, Tcl_StatBuf *buf) {
    const char *rel = lib_rel(Tcl_GetString(p));
    if (!rel)
        return -1;
    memset(buf, 0, sizeof(*buf));
    const TclLibEntry *f = lib_find(Tcl_GetString(p));
    if (f) {
        buf->st_mode = 0100644; /* regular file */
        buf->st_size = f->len;
        buf->st_mtime = 1;
        return 0;
    }
    if (lib_is_dir(rel)) {
        buf->st_mode = 0040755; /* directory */
        return 0;
    }
    return -1;
}
static int vfsAccess(Tcl_Obj *p, int mode) {
    const char *rel = lib_rel(Tcl_GetString(p));
    if (mode & 2 /* W_OK */)
        return -1; /* read-only filesystem */
    if (!rel)
        return -1;
    return (lib_find(Tcl_GetString(p)) || lib_is_dir(rel)) ? 0 : -1;
}
static Tcl_Channel vfsOpen(Tcl_Interp *ip, Tcl_Obj *p, int mode, int perm) {
    (void)mode;
    (void)perm;
    const TclLibEntry *f = lib_find(Tcl_GetString(p));
    if (!f) {
        if (ip)
            Tcl_SetResult(ip, "no such file in tcl library", TCL_STATIC);
        return 0;
    }
    MemChan *m = (MemChan *)ckalloc(sizeof(MemChan));
    m->f = f;
    m->pos = 0;
    char nm[40];
    snprintf(nm, sizeof nm, "tcllib%p", (void *)m);
    return Tcl_CreateChannel(&memChanType, nm, m, TCL_READABLE);
}
static Tcl_Obj *vfsListVolumes(void) {
    Tcl_Obj *l = Tcl_NewListObj(0, 0);
    Tcl_ListObjAppendElement(0, l, Tcl_NewStringObj(MOUNT, -1));
    Tcl_IncrRefCount(l);
    return l;
}
/* List the immediate children of `dir` matching `pattern`, honoring the glob `types` filter. When
 * `pattern` is NULL this is an *existence check* of `dir` itself (glob's final non-glob component). */
static int vfsMatchInDir(Tcl_Interp *ip, Tcl_Obj *result, Tcl_Obj *dir, const char *pattern,
                         Tcl_GlobTypeData *types) {
    const char *rel = lib_rel(Tcl_GetString(dir));
    if (!rel)
        return TCL_OK;
    size_t rl = strlen(rel);
    if (!pattern) {
        int isf = lib_find(Tcl_GetString(dir)) != 0;
        int isd = !isf && lib_is_dir(rel);
        if (!isf && !isd)
            return TCL_OK;
        if (types && types->type != 0) {
            int bit = isd ? TCL_GLOB_TYPE_DIR : TCL_GLOB_TYPE_FILE;
            if (!(types->type & bit))
                return TCL_OK;
        }
        Tcl_ListObjAppendElement(ip, result, dir);
        return TCL_OK;
    }
    char seen[64][128];
    int nseen = 0;
    for (int i = 0; i < tcl_library_n; i++) {
        const char *n = tcl_library[i].name;
        if (rl) {
            if (strncmp(n, rel, rl) != 0 || n[rl] != '/')
                continue;
            n += rl + 1;
        }
        const char *slash = strchr(n, '/');
        size_t cl = slash ? (size_t)(slash - n) : strlen(n);
        char comp[128];
        if (cl >= sizeof comp)
            continue;
        memcpy(comp, n, cl);
        comp[cl] = 0;
        int is_dir = (slash != 0); /* a component with more path below it is a directory */
        if (types && types->type != 0) {
            int bit = is_dir ? TCL_GLOB_TYPE_DIR : TCL_GLOB_TYPE_FILE;
            if (!(types->type & bit))
                continue;
        }
        if (!Tcl_StringMatch(comp, pattern))
            continue;
        int dup = 0;
        for (int s = 0; s < nseen; s++)
            if (strcmp(seen[s], comp) == 0) {
                dup = 1;
                break;
            }
        if (dup || nseen >= 64)
            continue;
        strcpy(seen[nseen++], comp);
        Tcl_ListObjAppendElement(ip, result, Tcl_ObjPrintf("%s/%s%s%s", MOUNT, rel, rl ? "/" : "", comp));
    }
    return TCL_OK;
}
static Tcl_Filesystem tcl_lib_vfs = {
    .typeName = "tcllibvfs",
    .structureLength = sizeof(Tcl_Filesystem),
    .version = TCL_FILESYSTEM_VERSION_1,
    .pathInFilesystemProc = vfsPathInFs,
    .statProc = vfsStat,
    .accessProc = vfsAccess,
    .openFileChannelProc = vfsOpen,
    .matchInDirectoryProc = vfsMatchInDir,
    .listVolumesProc = vfsListVolumes,
};

/* ---- driver ---------------------------------------------------------------------------------- */

static char src[1 << 20];

int main(int argc, char **argv) {
    Tcl_FindExecutable(argc > 0 ? argv[0] : "tclsh");
    Tcl_FSRegister(0, &tcl_lib_vfs);

    long len = 0;
    for (;;) {
        long r = read(0, src + len, (long)sizeof(src) - 1 - len);
        if (r <= 0)
            break;
        len += r;
        if (len >= (long)sizeof(src) - 1)
            break;
    }
    src[len] = 0;

    Tcl_Interp *interp = Tcl_CreateInterp();
    /* Point the library search straight at the VFS mount (skip the on-disk search entirely). */
    Tcl_SetVar2(interp, "env", "TCL_LIBRARY", MOUNT, TCL_GLOBAL_ONLY);
    Tcl_SetVar(interp, "tcl_library", MOUNT, TCL_GLOBAL_ONLY);

    if (Tcl_Init(interp) != TCL_OK) {
        const char *e = Tcl_GetStringResult(interp);
        fputs("Tcl_Init: ", stdout);
        fputs(e && e[0] ? e : "unknown error", stdout);
        fputc('\n', stdout);
    }

    int code = Tcl_Eval(interp, src);
    const char *res = Tcl_GetStringResult(interp);
    if (code != TCL_OK)
        fputs("error: ", stdout);
    if (res && res[0]) {
        fputs(res, stdout);
        fputc('\n', stdout);
    }

    Tcl_DeleteInterp(interp);
    return code == TCL_OK ? 0 : 1;
}
