#!/usr/bin/env python3
"""Generate `tcl_library.h` — the Tcl script library embedded as C byte arrays, so the full-init
driver (`tcl_init.c`) serves it through an in-guest `Tcl_Filesystem` VFS with **no real filesystem**.

Usage:  gen_tcl_library.py <tcl-source-library-dir> <out-header>

Embeds the minimal set that makes `Tcl_Init` + the common script commands work: `init.tcl` (the
bootstrap), `tclIndex` (auto-load index), the auto-loaded core scripts (`clock`/`parray`/`history`/…),
and `msgcat` (which `clock` requires). Timezone data (`tzdata/`, ~900 files) is deliberately excluded —
`clock -gmt 1` and `clock scan`/`format` in UTC work without it; local-zone conversion is a follow-up.
"""
import sys, os

# The library files to embed, relative to the source library dir. Kept small and explicit (not a
# whole-tree sweep) so the embedded blob stays ~270 KB, not the 6 MB the encoding/tzdata trees add.
FILES = [
    "init.tcl",           # the Tcl_Init bootstrap
    "tclIndex",           # auto_load index for the core scripts
    "auto.tcl",           # auto_mkindex / auto_execok helpers
    "clock.tcl",          # the `clock` command
    "history.tcl",        # the `history` command
    "package.tcl",        # `package` / `pkg_mkIndex`
    "parray.tcl",         # `parray`
    "word.tcl",           # `tcl_wordBreak*`
    "tm.tcl",             # Tcl Modules
    "safe.tcl",           # safe interpreters
    "msgcat/msgcat.tcl",  # message catalog — `clock` requires it
    "msgcat/pkgIndex.tcl",
]


def c_ident(path):
    return "lib_" + "".join(c if c.isalnum() else "_" for c in path)


def main():
    if len(sys.argv) != 3:
        sys.exit("usage: gen_tcl_library.py <library-dir> <out-header>")
    libdir, out = sys.argv[1], sys.argv[2]
    entries = []
    with open(out, "w") as h:
        h.write("/* Generated by gen_tcl_library.py — the Tcl script library as embedded byte arrays.\n")
        h.write(" * Do not edit; regenerate from a Tcl source tree's library/ dir. */\n")
        h.write("#ifndef TCL_LIBRARY_H\n#define TCL_LIBRARY_H\n\n")
        for rel in FILES:
            p = os.path.join(libdir, rel)
            if not os.path.exists(p):
                sys.stderr.write(f"note: skipping missing {rel}\n")
                continue
            data = open(p, "rb").read()
            ident = c_ident(rel)
            h.write(f"static const unsigned char {ident}[] = {{")
            h.write(",".join(str(b) for b in data))
            h.write(f"}};\n")
            entries.append((rel, ident, len(data)))
        h.write("\ntypedef struct { const char *name; const unsigned char *data; unsigned long len; } TclLibEntry;\n")
        h.write("static const TclLibEntry tcl_library[] = {\n")
        for rel, ident, n in entries:
            h.write(f'  {{ "{rel}", {ident}, {n} }},\n')
        h.write("};\n")
        h.write(f"static const int tcl_library_n = {len(entries)};\n\n")
        h.write("#endif\n")
    sys.stderr.write(f"embedded {len(entries)} library files → {out}\n")


if __name__ == "__main__":
    main()
